### ISSUE TITLE
Separate reading logic from label annotation in TC readers

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#188] opened 2015-06-09 14:14 UTC
Originally reported on Google Code with ID 188

```
Currently, TC readers are responsible for reading content, creating the CAS and assigning
appropriate labels (outcomes).
As discussed in today's meeting, this should be separated, so that plain DKPro Core
readers from the IO model can be reused as-is. To realize that, we need to add an annotator
(either by default or as configurable parameter) which converts existing annotations
(e.g. POS labels in case of the de.tudarmstadt.ukp.dkpro.tc.examples.io.BrownCorpusReader)
into ClassificationOutcomes.
```

Reported by `daxenberger.j` on 2014-10-07 13:31:13

**Comment by zesch** [comment] 2015-08-06 19:32
I have created a first version for this issue.
ValidityCheck is now split into a pre-preprocessing that checks early if the setup is valid (this is only run once for the first CAS) and a post-preprocessing step that checks for outcome & unit annotations (this is run for each CAS).

TwentyNewsgroupStandardReader demo shows how to use that for single label/document setup.

**Comment by daxenberger** [comment] 2015-08-07 11:35
Thanks.
TODO: test for unit/sequence/pair feature mode, and multi-label/regression learning mode.

**Comment by Horsmann** [comment] 2016-03-26 21:32
@daxenberger Can we close this issue, test cases exist ?

**Comment by reckart** [comment] 2016-03-26 21:45
I think only preparatory work was done - I think the actual issue wasn't addressed yet.

**Comment by daxenberger** [comment] 2016-03-26 23:30
yes, too early to close (see above). if necessary, we can move it to the next milestone.

**Comment by Horsmann** [comment] 2016-06-26 15:27
Regression demos are missing anyway see #369

The Pair demo is actually not compatible with the externalization because we use the same annotator for train and test which is a problem if two independent files have to be processed. Putting effort in rewriting the pair demos looks like waste of time to me. The principle should be clear enough with the other examples.

**Closed as completed by Horsmann** 2016-06-26 15:27 UTC
Labels: enhancement, Priority-Medium
